"""Add game_name to Room model

Revision ID: 1e2190726219
Revises: d9c9f3ca0f25
Create Date: 2024-08-16 18:37:18.709246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e2190726219'
down_revision: Union[str, None] = 'd9c9f3ca0f25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_column('created_by')
        batch_op.drop_column('game_name')

    # ### end Alembic commands ###
