"""Add users table

Revision ID: 7ae6aefbbc9c
Revises: d21cedb40d2e
Create Date: 2024-08-18 16:08:58.338881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ae6aefbbc9c'
down_revision: Union[str, None] = 'd21cedb40d2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('room_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.alter_column('game_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('created_by',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_index('ix_rooms_room_num')
        batch_op.create_index(batch_op.f('ix_rooms_room_num'), ['room_num'], unique=True)
        batch_op.create_unique_constraint('uq_rooms_id', ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_constraint('uq_rooms_id', type_='unique')
        batch_op.drop_index(batch_op.f('ix_rooms_room_num'))
        batch_op.create_index('ix_rooms_room_num', ['room_num'], unique=False)
        batch_op.alter_column('created_by',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('game_name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    # ### end Alembic commands ###
