"""empty message

Revision ID: e5556b5764b4
Revises: 7ae6aefbbc9c
Create Date: 2024-08-18 19:36:19.975636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5556b5764b4'
down_revision: Union[str, None] = '7ae6aefbbc9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass

def downgrade() -> None:
    pass